### ISSUE TITLE
Dist, locale and MANIFEST

### ISSUE THREAD

**Issue by ayushnawal** [sugarlabs/free-from-malaria-activity#3]
@quozl I am unable to understand the use of `dist`, `locale` and MANIFEST source files here. They are making the activity very heavy to clone to.

**Comment by quozl** [comment]
`dist` is not source file, but distribution zip files of bundles, made by `python setup.py dist_xo`,

`locale` is not source file, but compiled translation files.

`MANIFEST` is a list of files, and has been deprecated some years ago.

**Comment by ayushnawal** [comment]
Can we remove any of them along with `MANIFEST`, as they are making the repository too heavy :(

**Comment by quozl** [comment]
Sorry they are too big for you.

`dist` is 48 MB,

`locale` is 72 KB,

`MANIFEST` is 3.3 KB.

A `git clone` costs about 70 MB of network download, and 145 MB in a repository containing workspace, i.e. not bare.

Removing them won't reduce the download size of a `git clone`.  Once a file is added to a git repository, it will always exist unless the commit history is truncated.  Rewriting the history of this fork wouldn't change the upstream repository, and would make it harder to resolve changes between them.

I'd expect us to remove `MANIFEST`, `locale` and `dist` in activities in our control that we plan to release, but this activity doesn't seem likely to be released again any time soon.  https://github.com/wcpolpc/FreeFromMalaria/issues/2.

**Comment by ayushnawal** [comment]
@quozl  agreed, I will keep that in mind.
